default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: 1hrcloud_dev

test:
  <<: *default
  database: 1hrcloud_test

production:
  <<: *default
  database: 1hrcloud_prod
